package cn.cncc.community.community.model;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOMMENT.ID
     *
     * @mbg.generated Mon Feb 03 14:04:16 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOMMENT.PARENT_ID
     *
     * @mbg.generated Mon Feb 03 14:04:16 CST 2020
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOMMENT.TYPE
     *
     * @mbg.generated Mon Feb 03 14:04:16 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOMMENT.COMMENTATOR
     *
     * @mbg.generated Mon Feb 03 14:04:16 CST 2020
     */
    private Long commentator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOMMENT.GMT_CREATE
     *
     * @mbg.generated Mon Feb 03 14:04:16 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOMMENT.GMT_MODIFIED
     *
     * @mbg.generated Mon Feb 03 14:04:16 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOMMENT.LIKE_COUNT
     *
     * @mbg.generated Mon Feb 03 14:04:16 CST 2020
     */
    private Long likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOMMENT.CONTENT
     *
     * @mbg.generated Mon Feb 03 14:04:16 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TCOMMENT.ID
     *
     * @return the value of TCOMMENT.ID
     *
     * @mbg.generated Mon Feb 03 14:04:16 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TCOMMENT.ID
     *
     * @param id the value for TCOMMENT.ID
     *
     * @mbg.generated Mon Feb 03 14:04:16 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TCOMMENT.PARENT_ID
     *
     * @return the value of TCOMMENT.PARENT_ID
     *
     * @mbg.generated Mon Feb 03 14:04:16 CST 2020
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TCOMMENT.PARENT_ID
     *
     * @param parentId the value for TCOMMENT.PARENT_ID
     *
     * @mbg.generated Mon Feb 03 14:04:16 CST 2020
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TCOMMENT.TYPE
     *
     * @return the value of TCOMMENT.TYPE
     *
     * @mbg.generated Mon Feb 03 14:04:16 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TCOMMENT.TYPE
     *
     * @param type the value for TCOMMENT.TYPE
     *
     * @mbg.generated Mon Feb 03 14:04:16 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TCOMMENT.COMMENTATOR
     *
     * @return the value of TCOMMENT.COMMENTATOR
     *
     * @mbg.generated Mon Feb 03 14:04:16 CST 2020
     */
    public Long getCommentator() {
        return commentator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TCOMMENT.COMMENTATOR
     *
     * @param commentator the value for TCOMMENT.COMMENTATOR
     *
     * @mbg.generated Mon Feb 03 14:04:16 CST 2020
     */
    public void setCommentator(Long commentator) {
        this.commentator = commentator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TCOMMENT.GMT_CREATE
     *
     * @return the value of TCOMMENT.GMT_CREATE
     *
     * @mbg.generated Mon Feb 03 14:04:16 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TCOMMENT.GMT_CREATE
     *
     * @param gmtCreate the value for TCOMMENT.GMT_CREATE
     *
     * @mbg.generated Mon Feb 03 14:04:16 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TCOMMENT.GMT_MODIFIED
     *
     * @return the value of TCOMMENT.GMT_MODIFIED
     *
     * @mbg.generated Mon Feb 03 14:04:16 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TCOMMENT.GMT_MODIFIED
     *
     * @param gmtModified the value for TCOMMENT.GMT_MODIFIED
     *
     * @mbg.generated Mon Feb 03 14:04:16 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TCOMMENT.LIKE_COUNT
     *
     * @return the value of TCOMMENT.LIKE_COUNT
     *
     * @mbg.generated Mon Feb 03 14:04:16 CST 2020
     */
    public Long getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TCOMMENT.LIKE_COUNT
     *
     * @param likeCount the value for TCOMMENT.LIKE_COUNT
     *
     * @mbg.generated Mon Feb 03 14:04:16 CST 2020
     */
    public void setLikeCount(Long likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TCOMMENT.CONTENT
     *
     * @return the value of TCOMMENT.CONTENT
     *
     * @mbg.generated Mon Feb 03 14:04:16 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TCOMMENT.CONTENT
     *
     * @param content the value for TCOMMENT.CONTENT
     *
     * @mbg.generated Mon Feb 03 14:04:16 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}