package cn.cncc.community.community.mapper;

import cn.cncc.community.community.model.Tcomment;
import cn.cncc.community.community.model.TcommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TcommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TCOMMENT
     *
     * @mbg.generated Mon Feb 03 11:44:14 CST 2020
     */
    long countByExample(TcommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TCOMMENT
     *
     * @mbg.generated Mon Feb 03 11:44:14 CST 2020
     */
    int deleteByExample(TcommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TCOMMENT
     *
     * @mbg.generated Mon Feb 03 11:44:14 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TCOMMENT
     *
     * @mbg.generated Mon Feb 03 11:44:14 CST 2020
     */
    int insert(Tcomment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TCOMMENT
     *
     * @mbg.generated Mon Feb 03 11:44:14 CST 2020
     */
    int insertSelective(Tcomment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TCOMMENT
     *
     * @mbg.generated Mon Feb 03 11:44:14 CST 2020
     */
    List<Tcomment> selectByExampleWithRowbounds(TcommentExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TCOMMENT
     *
     * @mbg.generated Mon Feb 03 11:44:14 CST 2020
     */
    List<Tcomment> selectByExample(TcommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TCOMMENT
     *
     * @mbg.generated Mon Feb 03 11:44:14 CST 2020
     */
    Tcomment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TCOMMENT
     *
     * @mbg.generated Mon Feb 03 11:44:14 CST 2020
     */
    int updateByExampleSelective(@Param("record") Tcomment record, @Param("example") TcommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TCOMMENT
     *
     * @mbg.generated Mon Feb 03 11:44:14 CST 2020
     */
    int updateByExample(@Param("record") Tcomment record, @Param("example") TcommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TCOMMENT
     *
     * @mbg.generated Mon Feb 03 11:44:14 CST 2020
     */
    int updateByPrimaryKeySelective(Tcomment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TCOMMENT
     *
     * @mbg.generated Mon Feb 03 11:44:14 CST 2020
     */
    int updateByPrimaryKey(Tcomment record);
}